name: msc_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anyio=4.11.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - blosc=1.21.6=hd145fbb_1
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=hf139dec_1
  - brotli-bin=1.2.0=h8616949_1
  - brotli-python=1.2.0=py314h3262eb8_1
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cartopy=0.25.0=py314hc4308db_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cf-units=3.3.0=py314ha6d4590_1
  - cf-xarray=0.10.10=pyhd8ed1ab_0
  - cf_xarray=0.10.10=pyhd8ed1ab_0
  - cffi=2.0.0=py314h8ca4d5a_1
  - cftime=1.6.4=py314ha6d4590_2
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - choreographer=1.2.1=pyhcf101f3_0
  - click=8.3.1=pyh707e725_0
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - configobj=5.0.9=pyhd8ed1ab_1
  - contourpy=1.3.3=py314h00ed6fe_3
  - cpython=3.14.1=py314hd8ed1ab_100
  - cycler=0.12.1=pyhd8ed1ab_1
  - dask-core=2025.12.0=pyhcf101f3_1
  - debugpy=1.8.17=py314h93774dc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - docutils=0.22.3=pyhd8ed1ab_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - esmf=8.9.0=nompi_h9ee82fe_3
  - esmpy=8.9.0=pyhc455866_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.60.1=pyh7db6752_0
  - freetype=2.14.1=h694c41f_0
  - freexl=2.0.0=h3183152_2
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.14.1=he483b9e_0
  - giflib=5.2.2=h10d778d_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hdf4=4.2.15=h8138101_7
  - hdf5=1.14.6=nompi_hc1508a4_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - iris=3.14.1=pyha770c72_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=hc62ec3d_0
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kaleido-core=0.1.0=h35c211d_0
  - kiwisolver=1.4.9=py314hf3ac25a_2
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libaec=1.1.4=ha6bc127_0
  - libarchive=3.8.2=gpl_h889603c_100
  - libblas=3.11.0=2_he492b99_openblas
  - libbrotlicommon=1.2.0=h8616949_1
  - libbrotlidec=1.2.0=h8616949_1
  - libbrotlienc=1.2.0=h8616949_1
  - libcblas=3.11.0=2_h9b27e0a_openblas
  - libcurl=8.17.0=h7dd4100_0
  - libcxx=21.1.6=h3d58e20_0
  - libdeflate=1.25=h517ebb2_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=h750e83c_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgcc=15.2.0=h08519bb_12
  - libgdal-core=3.12.0=hfd904f9_1
  - libgfortran=15.2.0=h7e5c614_12
  - libgfortran5=15.2.0=hd16e46c_12
  - libhwy=1.3.0=hab838a1_1
  - libiconv=1.18=h57a12c2_2
  - libjpeg-turbo=3.1.2=h8616949_0
  - libjxl=0.11.1=h4ee1b5b_5
  - libkml=1.3.0=h450b6c2_1022
  - liblapack=3.11.0=2_h859234e_openblas
  - liblzma=5.8.1=hd471939_2
  - libmpdec=4.0.0=h6e16a3a_0
  - libnetcdf=4.9.3=nompi_habf9e57_103
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libpng=1.6.51=h380d223_0
  - librttopo=1.1.0=h16cd5d8_20
  - libsodium=1.0.20=hfdf4475_0
  - libspatialite=5.1.0=gpl_hb921464_119
  - libsqlite=3.51.0=h86bffb9_0
  - libssh2=1.11.1=hed3591d_0
  - libtiff=4.7.1=ha0a348c_1
  - libudunits2=2.2.28=h516ac8c_3
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.15.1=h7b7ecba_0
  - libxml2-16=2.15.1=ha1d9b0f_0
  - libxml2-devel=2.15.1=h7b7ecba_0
  - libzip=1.11.2=h31df5bb_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.7=h472b3d1_0
  - llvmlite=0.46.0=py314h85c3bf0_0
  - locket=1.0.0=pyhd8ed1ab_0
  - logistro=2.0.1=pyhcf101f3_0
  - loro=1.8.2=py314hf46512a_1
  - lz4-c=1.10.0=h240833e_1
  - lzo=2.10=h4132b18_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - marimo=0.18.0=py314h3439e5e_0
  - markdown=3.10=pyhcf101f3_1
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib=3.10.8=py314hee6578b_0
  - matplotlib-base=3.10.8=py314hd47142c_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - metpy=1.7.1=pyhd8ed1ab_0
  - minizip=4.0.10=hfb7a1ec_0
  - msgspec=0.20.0=py314h6482030_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=hb996559_0
  - narwhals=2.12.0=pyhcf101f3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf-fortran=4.6.2=nompi_h563d6fc_102
  - netcdf4=1.7.3=nompi_py314hf60e252_100
  - networkx=3.6=pyhcf101f3_0
  - numba=0.63.1=py314h385e359_0
  - numpy=2.3.5=py314hf08249b_0
  - openjpeg=2.5.4=h87e8dc5_0
  - openssl=3.6.0=h230baf5_0
  - orjson=3.11.4=py314ha7b6dee_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314hc4308db_1
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.47=h13923f0_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py314hca56afa_1
  - pint=0.25.2=pyhcf101f3_0
  - pip=25.3=pyh0d26453_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - proj=9.7.0=h3124640_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py314hd1e8ddb_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pykdtree=1.4.3=py314he6c707d_2
  - pymdown-extensions=10.17.2=pyhd8ed1ab_0
  - pyogrio=0.12.1=py314h687fbad_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.2=py314h56c42be_2
  - pyresample=1.34.2=py314h21b9a27_1
  - pyshp=3.0.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.1=pyhcf101f3_0
  - pytest-timeout=2.4.0=pyhd8ed1ab_0
  - python=3.14.0=hf88997e_102_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.14.1=h4df99d1_100
  - python-kaleido=1.2.0=pyhcf101f3_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py314h8d80757_1
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=pyh7db6752_0
  - pyzmq=27.1.0=py312hb7d603e_0
  - qhull=2020.2=h3c5361c_5
  - readline=8.2=h7cca4af_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rpds-py=0.30.0=py314ha7b6dee_0
  - scikit-learn=1.7.2=py314h2ca3526_0
  - scipy=1.16.3=py314h9d854bd_1
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py314h4eeafd1_2
  - simplejson=3.20.2=py314h6482030_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h01f5ddf_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sparse=0.17.0=pyhcf101f3_0
  - sqlite=3.51.0=hca40e9d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.50.0=pyhfdc7a7d_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=hf689a15_3
  - tomli=2.3.0=pyhcf101f3_0
  - tomlkit=0.13.3=pyha770c72_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.2=py314h6482030_2
  - tqdm=4.63.0=pyhd3eb1b0_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - udunits2=2.2.28=h516ac8c_3
  - unicodedata2=17.0.0=py314h6482030_1
  - uriparser=0.9.8=h6aefe2f_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - uvicorn=0.38.0=pyh31011fe_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - websockets=15.0.1=py314hcfd16f8_2
  - xarray=2025.12.0=pyhcf101f3_0
  - xerces-c=3.3.0=hd0321b6_0
  - xesmf=0.9.2=pyhd8ed1ab_0
  - xgcm=0.9.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - xwrf=0.0.5=pyhd8ed1ab_0
  - xxhash=0.8.3=h13e91ac_0
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h4132b18_3
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hd23fc13_2
  - zlib-ng=2.2.5=h55e386d_0
  - zstandard=0.25.0=py314hd1e8ddb_1
  - zstd=1.5.7=h8210216_2
prefix: /Users/Julie/opt/anaconda3/envs/msc_venv
